[package]
name = "transl"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Maycon F. Melo <@mayconfmelo>"]
license = "MIT-0"
description = "Easy and simple translations for words and expressions, with support for localization"
categories = [ "layout", "book" ]
keywords = [ "translation", "translator", "localization", "i18n", "l10n", "fluent" ]
repository = "https://github.com/mayconfmelo/transl"
exclude = [
  "dev/",
  "tests/",
  "docs/",
  "scripts/",
  ".git",
  ".github",
  ".gitignore",
  "justfile",
  "manual.typ"
]