name: Spellcheck
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  codespell:
    name: Codespell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.9
      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install codespell
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Run check
        run: just spell
  misspell:
    name: Misspell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install misspell
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Run check
        run: ./misspell -error